### PR TITLE
Update tr.po

### PR DESCRIPTION
**Pull request by TeknoMobil**
Hello I translated all the words

### CODE REVIEW

**Comment by jderose9** [comment]
Hi, thanks for submitting this @TeknoMobil ! Just so I am clear, the previous submission by @oltulu seems to be missing some phrases, and this is a more complete translation. Is that correct?

**Comment by TeknoMobil** [comment]
Thank you for this perfect add-on
Yes true, but some words are not in the language file

**Comment by jderose9** [comment]
Thanks! I understand that the previous submission was missing phrases, though I'm a little unclear why many of the existing translated phrases were changed? Do you consider this a more accurate translation?

**Comment by TeknoMobil** [comment]
Previous translation bad, wrong pronunciation errors were

**Comment by jderose9** [comment]
Ok, thanks again for your submission!

**Pull request merged**
