### PR TITLE
Configurable minimized application title font color

### LINKED ISSUE #678: [feature request] greyed-out font/icon for minimised windows
Once again thanks for this great extension. I'm finally making the switch to Wayland and this extension is the best way I've found to have a traditional taskbar on gnome-shell.

Previously, I was using tint2 (which only works on X), and I had it configured to grey out the taskbar entries for minimised windows. It looked like this:

tint2

With the icons and window titles for the minimised windows (the final two entries) greyed out somewhat.

It would be nice to have this option in dash to panel - it's useful to have an indication in the taskbar of whether a window is minimised or not. Obviously this only makes sense when 'ungroup applications' is enabled.

### PR DESCRIPTION
**Pull request by levacic**
Defaults to a mid-gray `#777777` color, but is configurable in the same menu where ungrouped application titles' font color can be configured.

Fixes #678

### CODE REVIEW

**Comment by levacic** [comment]
@charlesg99 Mind taking a look at this before it gets too stale? There's already a merge conflict with the changes made on `master` in the last few days, though it seems easy to resolve.

There's really no new code here, most of it is logic duplicated from other places - so it seems like it should be easy to review as well.

Thanks!

**Comment by levacic** [comment]
Hi Charles, no worries and thanks for the reply!

As a long-time user of the "ungrouped taskbar" interface, my experience is that it's _really_ helpful to be able to differentiate between minimized and unminimized apps at a glance - it gets very confusing otherwise. This is why I chose a darker color which is a more usable default in my opinion.

Just to be on the same page, is your suggestion mainly concerned with performance (ie. not subscribing to the `minimized` signal if the user doesn't care about a different minimized app title color), or keeping the extension as it is now out-of-the-box (ie. your "turned off by default" comment)?

I thought about having an extra switch for that, but the extension already has so many options, and I felt like it would have been needlessly cluttered with yet another switch, and leaned towards keeping things simple. It also seems like it would require more complicated code without much benefit - ie. we would also have to sync the signal connection/disconnection with the toggle switch state, for what's probably an insignificant performance improvement for users who do not wish a different color for minimized apps. However, I'm not too experienced with coding Gnome extensions, and I know how fragile it can be at times, so if you feel it would contribute to the overall performance of the extension, I can give it a shot when I find some extra time.

If your goal is to keep the same default behavior/look as the current one, how about just changing the default `#777777` into `#ffffff` (just like the default color for active/unminimized applications)? Once again, I think that a different color is a better default, and more in line with how other taskbars work, but it's cool as long as we can make it configurable.

Thanks for your time!

**Comment by charlesg99** [comment]
Hey Milos! This really isn't a performance concern and you're absolutely right that defaulting to the same color as the label would preserve the current behavior without adding yet another switch in the settings. If you can modify the default color and resolve the merge conflict, it'll be good to go for me! Thanks!

@jderose9 Good for you too?

**Comment by jderose9** [comment]
Everything looks good and the PR is working well for me so all good on this end. I agree with setting the default color back so we don't change existing behavior (and it personally would not be intuitive to me what the different color would be for). Just wanted to point out some of the template settings are #dddddd rather than #ffffff if you are changing those back as well.

Thanks so much for the submission @levacic!

**Comment by levacic** [comment]
Thanks both for your comments, I've rebased and resolved conflicts, and configured the default color for `group-apps-label-font-color-minimized` to always be the same as `group-app-labels-font-color` - you were right @jderose9, it's not `#ffffff` everywhere.

Let me know if you'd like me to do anything else here, happy to contribute!

**Comment by charlesg99** [comment]
Looks great to me! Thank you very much!

**Pull request merged**
