### PR TITLE
Gnome 46

### PR DESCRIPTION
**Pull request by philippun1**
Add Gnome 46 support.

Breaks compatibility to Gnome 45.

### CODE REVIEW

**Comment by darkblaze69** [comment]
https://gitlab.com/AndrewZaech/aztaskbar/-/commit/20c78662359a6056d2cce027c5430325c21de023

contains some tricks to preserve compatibility with 45 and 46. Maybe it could be possible to also serve one code for both versions.

**Comment by City-busz** [comment]
I created https://github.com/home-sweet-gnome/dash-to-panel/pull/2058 to update the CSS for GNOME 46.

**Comment by philippun1** [comment]
@City-busz Cherry picked your commit into this pull request.

**Comment by 4javier** [comment]
Gnome 46 landed on official Archlinux repo and dash-to-panel kill the whole shell, forcing it to restart with no extensions enabled.
It would be preferable to have a 46 compliant with small issues than the current situation.

**Comment by darkblaze69** [comment]
@4javier you probably need to update dash to panel to arch official 60-5, it is updated to all the changes for 46. It works for me on Arch.

**Comment by 4javier** [comment]
Thanks @darkblaze69 
I did that. I was hoping to not have to rely on repo version, and just use extensions.gnome.org.

**Pull request merged**
