### PR TITLE
window preview icon size change

### PR DESCRIPTION
**Pull request by hlechner**
window preview icon size will change based on font size
Discussion from #1099 

I think I found out a better way to do than the last pull request.

```javascript
let iconTextureSize = (Me.settings.get_int('window-preview-title-font-size') <= 16) ? 16 : 22;
```

just this line of change nothing else, basically it check the font size if less or equal to 16 then use 16 otherwise 22 (22 is the default now)

Since I saw the font size box is limited to maximum of 24px there is no need to over-complicate with other icon sizes, and also its attached to the font size, so there is no need to use scale factory or the height size on it.

I have tested (even with scale factory at 200%) and it seems working fine.

### CODE REVIEW

**Comment by hlechner** [comment]
Just an additional, I keep the `22` as for non 16 or below sizes since it was the original icon size, but I found out would be better if I can use `24` instead because of the icon sizes available on icon themes:
16px 24px 32px etc

the nautilus icon for example looks blurry on 22 but fine with 24

**Comment by jderose9** [comment]
24 sounds good.

**Comment by jderose9** [comment]
I tried this PR out and the icon looks too small to me in the default font size of 14px. We could keep it at 22 or 24 for 14 or maybe even 12px fonts but I don't think anyone would really go lower than that? I was thinking we would actually go larger at the max font size of 24px. Maybe we should just go with the separate setting if this is subjective?

**Comment by hlechner** [comment]
Got it, thinking about it I can see that not just personal opinion about the icon size but the font type, theme and the size of the window preview also change the perception of how big/small it should be, and in my case I do use a different font family on my theme and my window preview is smaller than default:
image

That's probably why it looks ok for me.

Would be great to have an option so I can change my icon size to 16px, I'm not sure if its possible to open the other PR or if I have to create a new one.

It's also possible that I change the default size (that you mention go larger at 24px) and still add the settings, if you prefer

**Comment by jderose9** [comment]
Closing in favor of #1099

**Pull request closed without merging**
