### PR TITLE
Fix quit from taskbar behaviour and text

### PR DESCRIPTION
**Pull request by philippun1**
Fixes the quit from taskbar behaviour with ungrouped windows (only close the selected one) and also the text for grouped windows (i.e. Quit 3 windows). (#1513  #1548)

### CODE REVIEW

**Comment by charlesg99** [comment]
Thanks Philipp!

**Comment by wennaspeedy** [comment]
I don't see "custom quit from taskbar" option in Dash to panel settings.

**Comment by charlesg99** [comment]
@nlpsuge Yes you're right, a fix for this was just pushed to master, so you can now quit the entire application if all the windows are associated with the panel (depends on your monitor and workspace isolation settings). Thanks!

**Comment by Alt37** [comment]
@charlesg99 
Unfortunately as of now it's not consistent across applications (e.g. with "Quit 2 windows" you can close both "Nautilus" windows but not 2 "GNOME Terminal" windows) but if you're using some hotkey for "Quit" (e.g. Shift+middle-click) it works properly.

**Pull request merged**
