### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by sbadux**
Add it.po translation as Italian translation

### CODE REVIEW

**Comment by charlesg99** [comment]
I'll leave it open a little before merging, so maybe by chance another Italian speaker will review it. Thanks!

**Comment by jderose9** [comment]
Thanks for the submissions @sbadux . If you have time/inclination, would you mind to update your submission to include the new settings import / export functionality that was added? We'll close master to new text changes at this point for v17.

Thanks again!

**Comment by sbadux** [comment]
@jderose9 Yes, no problem to update the translation with the last changes. Where can I find the new po file to translate?

**Comment by jderose9** [comment]
You will need to merge our master to your fork so you are up-to-date, then pull/clone to your machine. Then, you will want to run the commands `make potfile` and `make mergepo`.

**Comment by sbadux** [comment]
Thanks for help, but I'm really confused to use Git. I've tried to update my fork on GitHub, donwload the ZIP of the master and launch make potfile, but I can't understand how to do that.
Can I attach the po file here? Please also consider the use of translators-oriented services like Transifex or Crowdin. They can manage po files and they are much easier for us :)

**Comment by charlesg99** [comment]
Hey sbadux, yeah git is a bit confusing at first. I'll try to give you the steps:

First, get a local copy of your fork, then cd into it:
`git clone https://github.com/sbadux/dash-to-panel.git && cd dash-to-panel`

Create a link to the dash-to-panel repo over here:
`git remote add upstream https://github.com/home-sweet-gnome/dash-to-panel.git`

Get the latest version from here and merge it to your fork's master branch. Here in the text editor that'll show up after running the command, you can just leave the commit message as is:
`git fetch upstream master && git merge upstream/master`

Now we're ready to create the new po files:
`make potfile && make mergepo`

You can now edit the po/it.po file. When this is done, you can commit/push it to your fork and it will automatically update your merge request here. Do this with:
`git commit po/it.po -m 'Italian translation for v17' && git push origin master`

Let us know if you need additional information and thanks a lot!

**Comment by sbadux** [comment]
Thanks a lot! This worked fine. Just one more question: since I've already translated the it.po file, can I add the missing strings to that file or I need to start from scratch from the .pot file? I see the it.po file contains some missing strings so I guess it's updated, isn't it?

**Comment by charlesg99** [comment]
Hey sbadux, after running `make potfile && make mergepo`, you can directly edit po/it.po, which should already contain your previous translations. You can add the missing translations and then update your merge request with `git commit po/it.po -m 'Italian translation for v17' && git push origin master`. Thanks!

**Comment by charlesg99** [comment]
Hey sbadux, all good, your new translations have been added automatically to this merge request. You can confirm this by looking in the "files changed" tab up here. Thanks!

**Pull request merged**
