### PR TITLE
add option to change Show Desktop Button line color

### PR DESCRIPTION
**Pull request by hlechner**
image
image

default:
image
image

### CODE REVIEW

**Comment by jderose9** [comment]
Thanks so much @hlechner ! 

I'm a little unclear what the use case for this is? Is it hard to see on lighter background panel colors I guess? In that case would it be better to try to automatically use a dark color? It just seems a bit odd to me to have a setting to color a single line.

**Comment by hlechner** [comment]
I'm trying to achieve to turn my dash-to-panel panel as close as possible to the windows 10 panel, to have the same feel on my systems.

Dash-to-panel already does an wonderful job but there is just a few tweaks that still need to get the perfection.

The original color was too dark compared to the windows part (dash-to-panel use .2 of alpha but windows would be more a .5), since I don't want to change the original color of it (by pull request), and due to the dash-to-panel css i can't even change inside a theme.

So my ideia was to have an option to change the line color

**Comment by hlechner** [comment]
I think I went in a wrong path of adding options for each case in my pull requests, I believed that you guys would prefer than changing for everyone, sorry about that, but I understand that such small things should not pollute the settings.

if you still give me a chance to achieve it in a different way, here some ideas:

**(1) is just to change the .css file for a new color**
>it will keep it closer to windows (the dark theme at least), it's easy and changes a little bit, not sure if its the best option.
> from:
> ``.showdesktop-button {
> 	border: 0 solid rgba(200, 200, 200, .2);
> }``
> to
> ``.showdesktop-button {
> 	border: 0 solid rgba(200, 200, 200, .5);
> }``

**(2) change the css to apply it on it's parent instead of the button itself**
> (if not possible, create a new parent for receive it), right now it's not possible to change this line color on theme because the css target the ``showdesktop-button`` itself, so, even with `!important` on theme it won't change, however if create a new parent just to receive the style, it will allow to change the line color on theme.

**Comment by jderose9** [comment]
@hlechner No worries, this is a collaborative effort. Check out #1090 since I think it is a similar concern. If we can resolve that and your need I think it will be worth changing. I was thinking automatically detecting an appropriate color would be best but if that's not reasonable we can add the setting. If we add the setting, we should probably just call it the Show Desktop line color rather than use the term "override", and we can get rid of the style altogether.

**Comment by hlechner** [comment]
I believe it's possible to solve the issue #1090 without a settings option as well, I have worked partially on it, basically my idea is to get the panel color (if custom color enabled then get it otherwise get the theme color) and then check the brightness of it, I have tested this code and it works:
```javascript
        var c = this.dynamicTransparency.backgroundColorRgb.substring(1);      // strip #
        var rgb = parseInt(c, 16);   // convert rrggbb to decimal
        var r = (rgb >> 16) & 0xff;  // extract red
        var g = (rgb >>  8) & 0xff;  // extract green
        var b = (rgb >>  0) & 0xff;  // extract blue

        var luma = 0.2126 * r + 0.7152 * g + 0.0722 * b; // per ITU-R BT.709
```

If the brightness is above X then use the black with the alpha instead of white with alpha (default right now).

The only thing I didn't found out yet is how to get the panel color from theme, to get the custom color is possible to use this variable: `this.dynamicTransparency.backgroundColorRgb`.

Comparing the 20% of alpha (default now) to 50% of alpha:
20% alpha:
image
50% alpha:
image

**Comment by jderose9** [comment]
Yeah now that you mention it, I don't think I ever figured out how to get the theme CSS values - I don't know that it's available from the JS. I think that's how we ended up with so many settings in the first place. If the separate setting is truly the best way, we can go with that, I just wanted to try to think outside the box a little bit to try to help most people get something that looked good without having to fine tune every setting.

**Comment by charlesg99** [comment]
Hey guys! Yeah I think you can just use `this.dynamicTransparency.backgroundColorRgb`, this should always contain the panel's background color, even if it isn't explicitly defined in our settings. We sample the color from an offscreen "fake panel". Thanks!

**Comment by hlechner** [comment]
Thanks for the info @charlesg99 , since it should work I will use it then, I just probably calling it wrong or some other fault due my low experience with javascript.
```javascript
global.log("LOG= " + this.dynamicTransparency.backgroundColorRgb);
```
result (with custom color enabled):
`gnome-shell[948]: LOG= #353536`
result (without custom color):
`gnome-shell[948]: LOG= [boxed instance wrapper GIName:Clutter.Color jsobj@0x1465a99aecd0 native@0x55e68fcba110]`

the typeof shows an object but using JSON.stringify it returns an empty object.

I probably gonna figured out soon or later what I'm doing wrong, in last case I found an other way to get it:
`this.actor.get_style()` in this case I need to filter just the background-color from it.

**Comment by charlesg99** [comment]
Hey hlechner, I'm not sure how you're getting the `#355336` string, I always get an object (with a custom color or not) with a structure like Clutter.Color: `{ red: 255, green: 123, blue: 34, alpha: 120 };`. You could use that as, unfortunately, `get_style` only returns the "inline" styles and not the ones coming from the stylesheets (hence theme). Thanks!

**Comment by jderose9** [comment]
Closing in favor of 1108. Will revisit if that change isn't sufficient.

**Comment by hlechner** [comment]
Actually the 1108 doesn't change anything visually for me, since it's a dark one, but if I can change the default opacity from `20%` to `50%` or having a settings so I can change would solve it.

**Comment by jderose9** [comment]
@hlechner Would you mind updating this one to resolve any conflicts from your #1108 change and then I will merge this one as well? I was thinking if the color isn't overridden in the changes introduced here, it would get your 1108 behavior of making a choice between dark/light theme defaults. Thanks so much for all of your contributions!

**Comment by charlesg99** [comment]
Thanks a lot hlechner! I moved your useful brightness function to the utils file, let us know if that works for you.

**Comment by hlechner** [comment]
Thanks I will fix the conflict, I will make sure the #1108 still working when it's not overriden.

Also I will remove the term `Override` as you suggest earlier, if you prefer maybe a different label, since the normal stage do not have background-color just this margin color, it's even possible to maybe call it `show desktop button color` or any other label, by now I will just remove the override, if you prefer any alternatives just let me know.

**Comment by hlechner** [comment]
@charlesg99 thanks for that, really appreciated.

**Comment by jderose9** [comment]
@hlechner I think "override" is fine now since they are overriding the default color selection logic.

**Comment by hlechner** [comment]
Solved the conflicts and I also tested the master+pull request.

**Comment by jderose9** [comment]
Awesome, thanks so much @hlechner.  Working well on my end!

**Pull request merged**
