### PR TITLE
Fix transparency issue after overview has been shown and hidden

### PR DESCRIPTION
**Pull request by philippun1**
This is a workaround / potential fix for the transparency issue after exit overview.

### CODE REVIEW

**Comment by Alexmitter** [comment]
You probably already noticed that. When the Panel is black due to this bug and you enter the overview, it becomes transparent again while it is in the overview, it is just very hard to see. When you exit the overview it transforms into solid black again.
Something seems to set the panel to black when it is outside the overview and that code is most likely triggered when existing the overview as the bug only happens after entering and leaving the overview once.
Reloading the theme on overview exit is only really a workaround.

**Comment by Testing-XYZ** [comment]
> Reloading the theme on overview exit is only really a workaround.

I agree with Alexmitter. Reloading the theme by changing `Main.overview._hideDone` result in glitchy animation for now and might cause other problems in the future. 

Is there any good documentation on Main.overview?

**Comment by work-chausat** [comment]
If you use a override color for taskbar, after the button was clicked, the backgroud of taskbar changed to black, "override panel theme background color" doesn't work!!!!!

**Comment by Alexmitter** [comment]
To add some information, using the extension blur-my-shell (https://extensions.gnome.org/extension/3193/blur-my-shell/) fixes the black panel issue, something they do works.

**Comment by work-chausat** [comment]
@philippun1 
97e91e3 doesn't works after i locked my screen.

**Comment by Alexmitter** [comment]
@philippun1 For me it too freaks out sometimes when I activate the log screen with this patch, the error reported is: this.panel._leftCorner is undefined

**Comment by philippun1** [comment]
Yes, I'm aware a lot of things are broken right now, due to this change. That's why I made this PR draft again.
The old workaround was not really good. And I also tried blur-my-shell. But they seem to have similar issues (i.e. [#10](https://github.com/aunetx/blur-my-shell/issues/10), [#31](https://github.com/aunetx/blur-my-shell/issues/31)) at least there is no "real" transparency only a blurry panel.

Using the dtpSeconaryPanel (and not showing the top panel) fixes the transparency issue, but breaks a lot of other stuff. I don't know if this is the correct way to go, many things would have to be refactored to fix all the problem that are caused by this change.
@jderose9 Do you think this would be a proper solution? Sadly I do not know the code of dtp good enough (yet) to make an estimation.

**Comment by jderose9** [comment]
I think this was fixed by ec4e0784ae4a468ed7c5dc68693ae777f5cfe4c5.

**Pull request closed without merging**
