### PR TITLE
Explain how to actually customize it

### PR DESCRIPTION
**Pull request by dandv**
First time using the extension, and the docs weren't that obvious regarding how to customize it.

### CODE REVIEW

**Comment by jderose9** [comment]
Thanks @dandv ! The settings window can also be opened by right-clicking on the Show Applications (9-grid) button... we should probably mention that. I'm also thinking that rather than only providing apt installation instructions for GNOME Tweaks we could hop out to a wiki page (or external page, if one exists) that explain how to install on each linux distribution.

**Comment by dandv** [comment]
I've only used GNOME on Ubuntu :)

**Comment by smichel17** [comment]
You also don't *need* gnome tweaks to customize.

- If you installed via the gnome software center (eg, on Fedora), you there is a button to open Extension Settings from there
- I haven't used extensions.gnome.org for a while, but I think there is also a button to open extension preferences there, if you are using the browser plugin.

If someone installs from one of those sources, I don't think there's anything else you need to do; if it's unclear how to customize, it's a problem with those respective places and you don't need to fix it.

However, you also provide instructions for installing the development version from GitHub, and in that case, it's not obvious how to customize. So I think it would be a good idea to include instructions in the [Installation wiki page](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation) (and this would *also* help people who installed via other methods but didn't notice the settings buttons).

**Comment by jderose9** [comment]
Ok, I added a new Customization wiki page and linked it from the README FAQ. I added @dandv to the README credits but I'm going to close this one as I don't think needed based on the other changes. Thanks everyone!

**Pull request closed without merging**
