### PR TITLE
Display panel along percent of screen edge

### PR DESCRIPTION
**Pull request by marksvc**
Set the length of the panel according to a specified percent value, so
it can span only part of the screen edge.

Position the panel at the start, middle, or end of the screen edge, as
specified.

Tests okay with multiple monitors.

May also satisfy home-sweet-gnome/dash-to-panel#726

### CODE REVIEW

**Comment by marksvc** [comment]
I would like to limit the length of the panel to a percentage of the screen edge. Could we implement this feature with this pull request? See animation for behaviour.

dash-to-panel-percent

**Comment by jderose9** [comment]
@marksvc This is great! thanks so much.

I have a few random thoughts:

1. Does the length setting make more sense as a per-monitor setting or on the Style tab with the Panel Size option?
2. I think the length setting would be a little more usable as a slider rather than a spin button, if it fits.
3. We should probably rename existing Panel Size to Panel Height and your new "Length along screen" to Panel Width.
4. Let's disable position along screen edge when width is at 100%
5. If it's easy to dynamically rename the label for "Start" and "End" for the position setting to Top/Bottom and Left/Right when pane position changes, that might be more intuitive.
6. Let's plan to #726 open until we get some styling options in place.

Everything seems to be working well for me so far. Really appreciate the contribution.

@charlesg99 Do you have any concerns?

**Comment by jderose9** [comment]
One other thought - I was thinking we maybe should relocate the "Keep original gnome shell panel" option to a more prominent location on the Position tab since people will be more likely to prefer that setup now that the dock width can be adjusted? We could relabel it like "Taskbar mode: Single Panel / Separate Status and App Panels" or whatever makes sense.

**Comment by marksvc** [comment]
Thanks @jderose9 . 

1. Good question. I didn't realize until now that the "Order and positions on monitor" area was applying settings on sometimes a per-monitor basis. As I began thinking about this today, and the permutations of edges, orientations, and lengths, I reasoned that allowing per-monitor length and anchor setting may be more customization than needs to be implemented now. I decided against adding the additional customization, and moved the widgets to the Style tab. The current implementation already handles the use case of keeping the panel from unnecessarily using up so much space on a single screen.
But after finishing up my changes, I thought of a really good use case for per-monitor length setting. A small laptop could have the panel at 100% length, to have enough space to show the content. And a connected large monitor could have the panel at 50% length: large enough to show the content, but not so large that it unnecessarily uses up more screen space than it needs to. 
I won't plan to change it further right now to support per-monitor length setting, but certainly this could be implemented in the future.

2. I changed the length spin button to a scale (slider).

3. What do you think about "Panel thickness" and "Panel length"? Those work whether the panel is horizontal or vertical, so we don't have to update these UI labels depending on panel orientation. Or is it important that we use Height and Width?

4. That's a good idea. I turned off the sensitivity for position along screen edge / anchor when the panel is 100%.

5. I agree. I changed the labels for edge position / anchor to "Left, Center, Right" and "Top, Middle, Bottom", depending on whether the panel is horizontal or vertical. For cases where one panel is vertical and another monitor's panel is horizontal, I use "Start, Middle, End". I also kept START, MIDDLE, END in the schema.

> Keep original gnome-shell top panel

Yes, it could be made more prominent. Though since this extension is acting as a replacement for the top bar and the dash, making the "Keep original gnome-shell top panel" setting more prominent may ... cloud the purpose of the extension? I think this extension is significant because it incorporates the top bar and the dash together into a single panel. 

I won't include this in my update, but if you make the setting more prominent, you could consider using a label and combo box saying, 

Label: "Dash to Panel"
Combobox: 
 - "Replaces Gnome Shell top panel (default)"
 - "Complements Gnome Shell top panel"

And I recommend to put it at the top of the Style tab.
You could alternatively put it at the top of the Position tab.

I like your wording idea too, about mode, single or separate panels, if we found just the right wording.

I am pushing a second commit to the PR. In addition to changes discussed above, it:
 - Moves length and anchor to Styles tab.
 - Changes "Panel Size" to "Panel thickness"
 - Changes Position label to "Anchor"

See attached animation for dual monitor behaviour, in particular showing:
 - Widgets now on Style tab
 - Panel length scale (slider)
 - Anchor combobox item labels when multiple panels are all horizontal, all vertical, or a mix of horizontal and vertical
 - Anchor label and combobox having their sensitivity turned off when length is 100%

**Comment by marksvc** [comment]
Animation:

dash-to-panel-multimonitor

**Comment by jderose9** [comment]
Hey @marksvc, thanks so much. I agree with everything you said and thanks for thinking through the different use cases, and the new labels make sense to me.

I think I'd really like to move at least the new settings into a per-monitor configuration for the use case you described before merging to master, as it will be easier to not have to worry about migrating user settings into the new format down the road. So, I'm just waiting until I get a bit of time to work on that, but wanted to give you an update on why I hadn't merged yet.

**Comment by marksvc** [comment]
@jderose9 That sounds good. Thanks a lot!

**Comment by grexlort** [comment]
@marksvc hey I wanna to try out your changes, may I ask how did you build and test that functionality? I've fetched code from `panel-length` branch but after make file build settings app looks like current master build - any clue?

**Comment by marksvc** [comment]
@grexlort I had trouble getting the schemas to be easily picked up and used when testing. And so on a virtual machine I just used a brute-force approach, copying the new schema into /usr . I was using a command like the following, which builds, copies some files into /usr, and then runs gnome-shell in a nested session. I am sure there are cleaner and more elegant ways to do this that don't overwrite your files in /usr :-)
This assumes your git repo is in ~/src/dash-to-panel .

cd ~/src/dash-to-panel/ &&
make install &&
cp -f ~/src/dash-to-panel/schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml /usr/share/glib-2.0/schemas/ && 
cd /usr/share/glib-2.0/schemas/ && 
glib-compile-schemas . && 
sudo rm -rf /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com && 
sudo mkdir -p /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com && 
sudo cp -a ~/src/dash-to-panel/{*.js,*.ui,*.css,*.json,img,schemas} /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/ && 
dbus-run-session -- env MUTTER_DEBUG_NUM_DUMMY_MONITORS=2  gnome-shell --nested --wayland

**Comment by marksvc** [comment]
Today I worked on changing panel thickness, panel length, and anchor to be per-monitor settings. I am storing them as JSON strings in settings. I moved all 3 of thickness, length, and anchor out of the Style tab and into the Position tab, where they are now under the "Order and positions on monitor", "Apply changes to all monitors", and "Panel screen position" controls. 

I wasn't able to complete the changes today so I'll need to finish it up another time.

@jderose9 I hope I haven't stepped on any toes by having a go at this, or crashed into existing work in progress. We'll sort it out :-)

**Comment by jderose9** [comment]
@marksvc Awesome, no worries! I've been super busy recently. Let me know when you are ready and I will review and merge... and thank you!!

**Comment by marksvc** [comment]
Thanks @jderose9 . I finished the work making panel thickness, length, and anchor be per-monitor configurable. See animation below, showing all-monitor configuration and per-monitor configuration. The Anchor widget still uses vertical, horizontal, and mixed variations for its labeling, but with different considerations. (And it can even initially appear blank, if one panel is vertical, one is horizontal, "Apply changes to all monitors" is checked, and the panels have different anchor values set. Though that code may have been done after the below animation was made.)

dash-to-panel-per-monitor

**Comment by crivaronicolini** [comment]
Would it be possible to shrink the panel to a percentage when its hidden (so it only shows time and battery), and to expand it to 100% when the mouse is over it?

**Comment by marksvc** [comment]
@crivaronicolini That would do best in another PR, but yeah, I think someone would be able to do that.

**Comment by marksvc** [comment]
Hey @jderose9 , I hope you are well. Please let me know if there is anything I can explain or change in the PR. 
It grew from its initial patch; if any of it doesn't match with your goals or desired design, maybe we can talk about that and get it to conform.

**Comment by jderose9** [comment]
@marksvc This all looks great to me. Big apology for the lengthy delay. Thank you so much!

**Comment by marksvc** [comment]
Thanks so much @jderose9 !

**Pull request merged**
