### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by orhanenginokay**

### CODE REVIEW

**Comment by jderose9** [comment]
Thank you very much for your time in completing this. @TeknoMobil has also recently submitted a pull request with a different set of translations.

As I have no familiarity with the language, I am hoping that you could come to a consensus regarding which version seems more accurate?

Thanks again to you both for your time!

**Comment by orhanenginokay** [comment]
I am happy to help it. 

I changed maybe 3 or 4 parts, mostly I added missing parts. If you compare old tr.po and new tr.po, You will some missing parts translated. 

Thank you

**Comment by orhanenginokay** [comment]
I quick check TeknoMobil translate file. It seems quite good with out some mistakes

**Comment by jderose9** [comment]
Ok, I took TeknoMobil's version and will close this one. If you have any further revisions please feel free to submit them. Thank you for your time!

**Pull request closed without merging**
