### PR TITLE
Use fallback color if dominant color cannot be extracted

### LINKED ISSUE #1244: Missing Indicator on Firfox Developer and Nightly
**Describe the bug**
When I run programs like Firefox Developer or Firefox Nightly there doesn't appear to be an indicator for them.  These programs were installed by downloading the tar file and extracting them and then run them.  I've installed Firefox Beta and Firefox ESR in the same manner but do not have issues with them.

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
GNOME Shell 3.38.1

**Dash-to-Panel version**
version: 40

**Where was Dash-to-Panel installed from?**
AUR

**Screenshots / Video captures**
Dash_to_Panel01

**Additional Info**

### PR DESCRIPTION
**Pull request by danielhuang**
Some applications, such as `ffplay`, do not have an icon. In such cases, the application will have no running indicator. This ensures that such cases will have a running indicator using a fallback color.

Possibly fixes #1244

### CODE REVIEW

**Comment by maydayv7** [comment]
(Bumping, I am affected by this issue)

**Comment by charlesg99** [comment]
Looks good, do we know what throws an exception in there in this case? Just wondering

**Comment by danielhuang** [comment]
It's been a while since I looked at this, but I remember it being that the `_getIconPixBuf` call was throwing an error instead of returning null.

**Comment by charlesg99** [comment]
Thanks, this was fixed by another PR, so I'll close this one.

**Pull request closed without merging**
