### PR TITLE
Update to Gnome 40

### PR DESCRIPTION
**Pull request by philippun1**
This makes dash-to-panel usable on Gnome 40.

- removed pre GS40 "show apps" animation, since it no longer worked correctly and did not match with the new animation. Please use gnome-tweaks to (de)activate animations.
- added a "disable overview on startup" option. Does not work correctly after resume and extension enable, also seems to be bugged on Xorg.
- each pref dialog tab can now scroll individually, so the tab bar is always visible
- breaks compatibility with pre GS40 versions, so it would probably be best to keep a separate legacy branch for older versions.
- show overview only works on primary monitor for now
- probably some regressions due to the merge with the latest changes from upstream/master

### CODE REVIEW

**Review by blackjackshellac — COMMENTED** [review]
shell-version should probably be limited to [ "40" ]

**Comment by jatin-cbs** [comment]
Great work ! Also can you set update-to-gnome40 as the default branch on https://github.com/philippun1/dash-to-panel  (simply in your repository settings). for people reaching to that repo and also for a better feedback.

**Comment by cthbleachbit** [comment]
Thank you for this port. At least the basic panel is working.

This port seems to have issue on dual monitors. The overview screen has overlapping windows on one monitor and none on the other...

My 2nd screen:

2021-04-10 04-31-28 的屏幕截图

**Comment by vivaeltopo** [comment]
@cthbleachbit works fine on my dual monitor setup

**Comment by DarkKowalski** [comment]
> Thank you for this port. At least the basic panel is working.
> 
> This port seems to have issue on dual monitors. The overview screen has overlapping windows on one monitor and none on the other...
> 
> My 2nd screen:
> 
> 2021-04-10 04-31-28 的屏幕截图

I have encountered exactly the same issue on my secondary display.

**Comment by Taijian** [comment]
OK, this is *mostly* working for me on Arch.

However, there is one issue that I cannot seem to get working: I cannot for the life of me reorder the items on the panel like I used to be able to in prior versions. This might be related to the issue that there seem to be a duplication of the settings boxes as seen here: 
Bildschirmfoto von 2021-04-10 13-38-46

What's more, every time I toggle the position of the panel (right, left, top, bottom) and extra set of settings boxes appears...

So, something seems to be wrong here

**Comment by tognee** [comment]
Some issues I found:
- Can't reorder or hide/unhide items on the panel
- The "Ignore panel opacity" option is not respected after closing the activity view
- Sometimes the second screen glitches out when opening the activity view

**Comment by MuhammedTaha02** [comment]
Not worked for me. @philippun1 

image

**Comment by tognee** [comment]
@MuhammedTaha02 Make sure you've installed the correct version, that error is the same from the main branch

**Comment by MuhammedTaha02** [comment]
> @MuhammedTaha02 Make sure you've installed the correct version, that error is the same from the main branch

@tognee I forked this branch : https://github.com/philippun1/dash-to-panel/tree/update-to-gnome40

**Comment by blackjackshellac** [comment]
The error suggests you're on the main branch.  Make sure you checkout the update-to-gnome40 branch after cloning,
```
git checkout -t origin/update-to-gnome40
```

**Comment by MuhammedTaha02** [comment]
> The error suggests you're on the main branch. Make sure you checkout the update-to-gnome40 branch after cloning,
> 
> ```
> git checkout -t origin/update-to-gnome40
> ```

I tried this and worked. But there are some mistakes. @philippun1 
1) Import settings, export features do not work.
image

2)There is a delay when opening and closing the Activities menu.

3)There is a black zone under virtual desktops.
image

I did not find any other problems. The plugin works fine except for these issues. Thanks for working.

**Comment by Taijian** [comment]
Wow, so much better now! My complaints from before seem to have been fixed by this latest round of commits!

Really impressive work!

**Comment by rgarber11** [comment]
Thank you so much for undertaking this! I installed this in Arch, but it did not work. The extension gave the error "no JS module "_overview" found in search path". It could not be enabled, but it cleared everything out of my top bar.

**Comment by MuhammedTaha02** [comment]
> > The error suggests you're on the main branch. Make sure you checkout the update-to-gnome40 branch after cloning,
> > ```
> > git checkout -t origin/update-to-gnome40
> > ```
> 
> I tried this and worked. Thanks @blackjackshellac
> 
> But there are some mistakes. @philippun1
> 
> 1. Import settings, export features do not work. I guess it's trying to call something on gtk3.
>    image
> 
> 2)There is a delay when opening and closing the Activities menu.
> 
> 3)There is a black zone under virtual desktops.
> image
> 
> I did not find any other problems. The plugin works fine except for these issues. Thanks for working.

@philippun1 I installed the new commits to my computer. And I ran the plugin. The black line issue at the bottom of the screen did not fix. And the option to import settings is gone. I cannot import my settings.

**Comment by SCN-Nate** [comment]
`fatal: repository 'https://github.com/philippun1/dash-to-panel/tree/update-to-gnome40/' not found`
Why am i getting this error and when i clone from 
[](https://github.com/home-sweet-gnome/dash-to-panel)
and run 
`git checkout -t origin/update-to-gnome40`
nothing happens

**Comment by hrdwrrsk2** [comment]
> @philippun1 I installed the new commits to my computer. And I ran the plugin. The black line issue at the bottom of the screen did not fix. And the option to import settings is gone. I cannot import my settings.

speaking about bottom black gap issue, this also occurs with dash-to-dock and window-list extension (or any extension that moves panel to bottom/creating additional bottom panel) and standalone dock app such as Plank. see my comment in micheleg/dash-to-dock#1402. this is a upstream gnome-shell issue

**Comment by cthbleachbit** [comment]
It turns out that the secondary screen glitch in overview would only occur if two monitors have different resolution. My secondary monitor is on 2K when the primary (on the left) is 1080P.

Note that the transparent region in the screenshot actually looks pretty glitched to my naked eye on screen.

2021-04-11 23-59-46 的屏幕截图

**Comment by foldfelis** [comment]
The transparent effect is not working after i switch to navigation  and switch back.
Great work and thanks in advance.

2021-04-12 13-31-44 的螢幕擷圖
2021-04-12 13-31-48 的螢幕擷圖
2021-04-12 13-31-52 的螢幕擷圖

**Comment by PHLAK** [comment]
@SCN-Nate

> Why am i getting this error and when i clone from

This is happenning because the `update-to-gnome40` branch is a PR from @philippun1. You need to pull it from his repository.

    git remote add philippun1 https://github.com/philippun1/dash-to-panel.git
    git fetch phlilippun1 update-to-gnome40
    git checkout update-to-gnome40

**Comment by Horrih** [comment]
Just tried out yout branch yesterday.
Despite a few remaining glitches it mostly works on arch ! 
My only remaining issue was the duplication in the reordering of panel entries. 
Thank you for your fantastic job

**Comment by MuhammedTaha02** [comment]
> > @philippun1 I installed the new commits to my computer. And I ran the plugin. The black line issue at the bottom of the screen did not fix. And the option to import settings is gone. I cannot import my settings.
> 
> speaking about bottom black gap issue, this also occurs with dash-to-dock and window-list extension (or any extension that moves panel to bottom/creating additional bottom panel) and standalone dock app such as Plank. see my comment in [micheleg/dash-to-dock#1402](https://github.com/micheleg/dash-to-dock/pull/1402). this is a upstream gnome-shell issue

Hmm. I understand.

**Comment by PHLAK** [comment]
Checked out this branch on Gnome 40 on Arch and it seems to be working well for my purposes.

**Comment by MuhammedTaha02** [comment]
@philippun1 Why did you remove the restore settings option? For some people, that option is important.

image

**Comment by MuhammedTaha02** [comment]
EDIT: Import settings from terminal;

BASH/ZSH
for i in $(cat <SETTINGSFILE>); do
        var1=$(echo $i | cut -d"=" -f1)
        var2=$(echo $i | cut -d"=" -f2)
        gsettings set org.gnome.shell.extensions.dash-to-panel $var1 $var2
end

FISH
for i in (cat <SETTINGSFILE>)
        set var1 (echo $i | cut -d"=" -f1)
        set var2 (echo $i | cut -d"=" -f2)
        gsettings set org.gnome.shell.extensions.dash-to-panel $var1 $var2
end

**Comment by philippun1** [comment]
@MuhammedTaha02 Things that do not work right now are hidden.

**Comment by MuhammedTaha02** [comment]
> @MuhammedTaha02 Things that do not work right now are hidden.

I understand :thinking:

**Comment by dylanmtaylor** [comment]
Thank you so much for working on this, I really hope to see this land in the repo when it's done! :)

**Comment by SCN-Nate** [comment]
> @SCN-Nate
> 
> > Why am i getting this error and when i clone from
> 
> This is happenning because the `update-to-gnome40` branch from @philippun1. You need to pull it from their repository.
> 
> ```
> git remote add philippun1 https://github.com/philippun1/dash-to-panel.git
> git fetch phlilippun1 update-to-gnome40
> git checkout update-to-gnome40
> ```

I tried and it says `fatal: not a guy repository` I'm sorry can you guide me I suck at the terminal

**Comment by PHLAK** [comment]
@SCN-Nate It looks like I had a typo in the second line: `phlilippun1` -> `philippun1`

See if it works with that correction.

**Comment by SCN-Nate** [comment]
> @SCN-Nate It looks like I had a typo in the second line: `phlilippun1` -> `philippun1`
> 
> See if it works with that correction.
> 
> Alternatively clone @philippun1's repo directly and use that (looks like the `update-to-gnome40` branch is the default).
> 
> ```
> git clone https://github.com/philippun1/dash-to-panel
> ```

Finally got the thing working thx

**Comment by rgarber11** [comment]
I'd just like to note that my problems were due to having the standard version also installed via the AUR. Uninstalling it solved the problem. All features that I use are working well (Hot corner, AppMenu, Currently opened apps, along with date, RightBox and System Menu.) This is on a system with the Gnome40 Dash to Dock, along with Pop Shell. I also have no problems with any black bars on the bottom of my screen.
2021-04-13-052315_1919x1079_escrotum

**Comment by x80486** [comment]
It works fine for me also. I'm using Arch Linux and GNOME `40.x` 👍🏻

**Comment by SCN-Nate** [comment]
we gonna remove arrows? 
[https://imgur.com/a/Sg55e08](url)

**Comment by PHLAK** [comment]
> we gonna remove arrows?

@SCN-Nate Did you post that here by mistake? This looks like a comment for the [Sound Input & Output Device Chooser](https://extensions.gnome.org/extension/906/sound-output-device-chooser/) extension.

**Comment by SCN-Nate** [comment]
> > we gonna remove arrows?
> 
> @SCN-Nate Did you post that here by mistake? This looks like a comment for the [Sound Input & Output Device Chooser](https://extensions.gnome.org/extension/906/sound-output-device-chooser/) extension.

nope cause its the panel doing that

**Comment by philippun1** [comment]
@SCN-Nate I removed the arrow related code, so the arrows should theoretically be gone. I have arrows with or without the extensions, so I cannot really tell... (At least if we are speaking of the arrow at the top of the box which directs to the panel)

**Comment by cynecx** [comment]
@philippun1 I’ve noticed with an older checkout (1-2 days ago) that transparency is somewhat broken. I mean it works at first but after toggling the activity overview and back the taskbar is black.

**Comment by PHLAK** [comment]
When clicking the "Show Applicaitons" button the app icons "slide" in along the bottom from the left then move up into position which isn't very smooth and is slower than normal (i.e. <kbd>Super</kbd> + <kbd>A</kbd>).

[Here's a video of the problem](https://youtu.be/vYPa0YaBKIY). The first two times the app grid is shown using <kbd>Super</kbd> + <kbd>A</kbd>. The second two times were using the "Show Applications" button on the dash.

**Comment by bearoso** [comment]
> When clicking the "Show Applicaitons" button the app icons "slide" in along the bottom from the left then move up into position which isn't very smooth and is slower than normal (i.e. Super + A).
> 
> [Here's a video of the problem](https://youtu.be/vYPa0YaBKIY). The first two times the app grid is shown using Super + A. The second two times were using the "Show Applications" button on the dash. Notice how the icons slide up vs slide "in" then up.

If you move the panel to the top this doesn't happen. It's because the transition uses sizes and positions assuming everything is stock. The transition will move everything to where things should be without the extension, then snap immediately to the final location, or it'll snap to a different starting position before the transition happens. There's lots of little nits like this because the whole shell overview structure changed. 

Something similar I noticed is that if you start the extension after the shell is running as opposed to at the same time, space is reserved on the bottom of the overview application switcher for the stock gnome dock, even though it isn't there.

**Comment by chrisjbillington** [comment]
> @philippun1 I’ve noticed an issue with an older checkout (1-2 days ago) that transparency is somewhat broken. I mean it works at first but after toggling the activity overview and back the taskbar is black. I didn’t have time to test out the recent changes yet.

I see this in the latest commit as well.

**Comment by philippun1** [comment]
I've removed the old show apps animation completely, it does not work correctly and it is no longer used by gnome-shell anyways. You can use gnome-tweaks to (de)activate the new animation.

Also I'm aware of the transparency issue, but I still have no idea why it is not drawn correctly.

**Comment by MuhammedTaha02** [comment]
> I've removed the old show apps animation completely, it does not work correctly and it is no longer used by gnome-shell anyways. You can use gnome-tweaks to (de)activate the new animation.
> 
> Also I'm aware of the transparency issue, but I still have no idea why it is not drawn correctly.

Ewlsh seems to have fixed this problem
https://github.com/micheleg/dash-to-dock/pull/1402#issuecomment-819147766

**Comment by amrmsaraya** [comment]
Workspaces shadow problem exist when Panel Intellihide is OFF, when i turn it one shadow problem disappear.

Intellihide OFF
Screenshot from 2021-04-17 14-58-38

Intellihide ON
Screenshot from 2021-04-17 14-58-48

**Comment by hrdwrrsk2** [comment]
> Workspaces shadow problem exist when Panel Intellihide is OFF, when i turn it one shadow problem disappear.
> 
> Intellihide OFF
> Screenshot from 2021-04-17 14-58-38
> 
> Intellihide ON
> Screenshot from 2021-04-17 14-58-48

upstream bug, this also occurs with dash-to-dock and window-list extension (basically, extension/apps that creates bottom panel will causes this. also this reason why I temporarily switched to Budgie/Xfce desktop but kept GNOME installation on my arch install)

i'm sure it will fixed in upstream but i doubt about it, native window placement extension also causes stretching workspace thumbnail but only in all apps view, not activities overview. so it's neither gnome-shell overview sizing calculation issue after major UI change or (maybe) mutter issue

**Comment by PHLAK** [comment]
> I've removed the old show apps animation completely

Thanks, this is _much_ cleaner.

**Comment by DarkKowalski** [comment]
Still not working well when it's connected to dual monitors.
I am using Arch Linux latest stable build.

image

**Comment by philippun1** [comment]
@DarkKowalski Do you use wayland or xorg? And can you please post the output from "journalctl -f -o cat /bin/gnome-shell" right after the issue occurs.
Multi monitor works fine for me on Ubuntu and Manjaro, so this will be difficulut to investigate.

**Comment by CorvetteCole** [comment]
@philippun1 when scrolling on the panel to switch workspaces is enabled, scrolling on the volume icon to change the volume will also switch workspaces. In previous Gnome versions this worked as intended. I couldn't find a place to file a bug report so I figured I would just let you know here

**Comment by chrisjbillington** [comment]
> @philippun1 when scrolling on the panel to switch workspaces is enabled, scrolling on the volume icon to change the volume will also switch workspaces. In previous Gnome versions this worked as intended. I couldn't find a place to file a bug report so I figured I would just let you know here

For reference, here's a previously resolved issue on this:
https://github.com/home-sweet-gnome/dash-to-panel/issues/702

**Comment by DarkKowalski** [comment]
> @DarkKowalski Do you use wayland or xorg? And can you please post the output from "journalctl -f -o cat /bin/gnome-shell" right after the issue occurs.
> Multi monitor works fine for me on Ubuntu and Manjaro, so this will be difficulut to investigate.

I am using wayland and here are logs from journalctl
```
setup_framebuffers: assertion 'width > 0' failed
Can't update stage views actor ClutterActor is on because it needs an allocation.
```

**Comment by CorvetteCole** [comment]
hey @philippun1 @chrisjbillington I fixed this bug and filed a merge request at the fork https://github.com/philippun1/dash-to-panel/pull/1

**Comment by Testing-XYZ** [comment]
@philippun1 refreshing the theme with `'Main.loadTheme();'` after overview seems to address the issue of transparency

**Comment by DarkKowalski** [comment]
> > @DarkKowalski Do you use wayland or xorg? And can you please post the output from "journalctl -f -o cat /bin/gnome-shell" right after the issue occurs.
> > Multi monitor works fine for me on Ubuntu and Manjaro, so this will be difficulut to investigate.
> 
> I am using wayland and here are logs from journalctl
> 
> ```
> setup_framebuffers: assertion 'width > 0' failed
> Can't update stage views actor ClutterActor is on because it needs an allocation.
> ```

I tried to figure out how to reproduce this situation, finding out that:
1. a built-in 2560x1600(16:10) display on the left, 150% scale
2. a 2560x1440(16:9) display on the right, 100% scale
3. align them like:
image

**Comment by cynecx** [comment]
@Testing-XYZ Where exactly did you put that call? I can't seem to reproduce this by putting it in `_updateAlphaAndSet`.

**Comment by philippun1** [comment]
@Testing-XYZ I tried to call it in a overview hiding callback, but it did not help.
I have noticed if you change any theme gradient settings, the opacity (and gradient) works again. Also if I add the gradient code to the opacity settings callbacks, these settings will trigger the opacity (and gradient) to come back.
At the moment I would assume this is an upstream timing issue?

@DarkKowalski I will try to reproduce this as soon as possible.

**Comment by hebrewd** [comment]
@philippun1 @DarkKowalski 
I'm facing the same issue, actually with the X11 backend for gnome, the wayland backend doesn't seem to show the issue.
I have a dual monitor with a 1080p and 1440p setup.

**Comment by Idiot64** [comment]
just use wayland -v-

**Comment by philippun1** [comment]
There seems to be a problem with settings the focused monitor, I commented some code out, multi monitor works now under Xorg as well. Additionally this seems to have fixed the opacity issue. At least under Xorg, under Wayland it only works on the main panel somehow.

**Comment by jderose9** [comment]
THANK YOU so much for the huge effort so far @philippun1!

I'm a little hesitant to merge without hearing from @charlesg99 because so far the extension has maintained broken backward compatibility. I think it will be possible to make things work on gtk3 and 4 by dynamically loading a different Settings.ui file for each. That said, with the large divergence in the Gnome 40 UI it seems like it will be carrying a lot of baggage to try to continue to support < 40.

On the flip side, the built-in auto-update mechanism isn't smart enough to grab only new releases applicable for a particular version of GNOME and I hate to break people's stable system by having them grab and install a version that doesn't work. So minimally, I think it makes sense to either fork to a different repo/extension-id or release a version for <3.40 with a more intelligent auto-update for a period of time before breaking compatibility.

For reference, here are the documents I was using to review underlying breaking changes:
https://gjs.guide/extensions/upgrading/gnome-shell-40.html
https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html

Some thoughts on outstanding issues:

- I'm not sure how you guys are getting the transparency to work. From what I can tell, [inline CSS styles are no longer supported](https://gjs.guide/extensions/upgrading/gnome-shell-40.html#provide-css-file-for-prefs), which are used to color the panel and make it transparent. So anywhere styles are specified inline, would be not working. I think the opacity can be fixed pretty easily with a bunch of CSS classes but I don't know about the places an arbitrary color can be configured, such as the panel color override. Might need a DrawingArea behind the panel.

- With the panel at the bottom, the overview closing animation is very janky. It still thinks there is a panel at the top of the screen. I spent a couple hours trying to fix it without success. I was able to disable the animation completely pretty simply but I can't find a good hook to have the overview re-allocated correctly without pulling a large amount of GS code in, and I don't exactly understand how StAdjustment is working and there is no documentation.

**Comment by philippun1** [comment]
@jderose9 Keeping backwards compatibility will result in a lot of duplicate code, not only the settings ui, but also the whole callback handling, and a lot of other stuff. Maybe you could create a dash-to-panel-ng repo as a starting point.

Is the update mechanism still being used? You can always use extension.gnome.org with the browser plugin to get updates.

**Comment by reagentoo** [comment]
How can I test this?
I've built from `philippun1:update-to-gnome40` branch. But I don't see dash-to-panel in the extension list.

```
$ equery f gnome-shell-extension-dash-to-panel
 * Searching for gnome-shell-extension-dash-to-panel ...
 * Contents of gnome-extra/gnome-shell-extension-dash-to-panel-41_pre:
/usr
/usr/share
/usr/share/doc
/usr/share/doc/gnome-shell-extension-dash-to-panel-41_pre
/usr/share/doc/gnome-shell-extension-dash-to-panel-41_pre/README.html
/usr/share/doc/gnome-shell-extension-dash-to-panel-41_pre/README.md.bz2
/usr/share/glib-2.0
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
/usr/share/gnome-shell
/usr/share/gnome-shell/extensions
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/Settings.ui
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/convenience.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/highlight_stacked_bg.svg
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/highlight_stacked_bg_2.svg
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/highlight_stacked_bg_3.svg
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/intellihide.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/cs/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/de
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/de/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/de/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/es/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/fr
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/fr/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/fr/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/gl
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/gl/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/gl/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/hu
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/hu/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/hu/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/it
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/it/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/it/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ja
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ja/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ja/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/kk
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/kk/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/kk/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pl
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pl/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pl/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pt_BR
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pt_BR/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/pt_BR/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/ru/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/sv
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/sv/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/sv/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/tr
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/tr/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/tr/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/uk
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/uk/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/uk/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_CN
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_CN/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_CN/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_TW
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_TW/LC_MESSAGES
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/locale/zh_TW/LC_MESSAGES/dash-to-panel.mo
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/metadata.json
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelPositions.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/progress.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/proximity.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/stylesheet.css
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/transparency.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js
/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js
```

**Comment by jderose9** [comment]
If we make a new repo for GS 3.40, the issues, PRs, etc will no longer be attached, and who knows how many broken links from various external sites.

I think my plan will be to tag a new/final 3.38 release today without the auto-update, and then in a week release the v40 under the same repo without support for < 3.40, unless @charlesg99 feels differently.

**Comment by Srcky** [comment]
Having some of the problems as described above but on openSUSE Tumbleweed, latest release, using xOrg. With dual monitors, only 1 panel is transparent, on other the panel background is black. 
Screenshot from 2021-05-04 19-49-21

After locking and then unlocking the computer, extension fails, and the default panel is loaded. After that in extensions panel there is a warning
Screenshot from 2021-05-04 19-52-48

Extension is then unusable, unless installed again.

**Comment by philippun1** [comment]
@jderose9 Trying to rebase to new upstream/master
@Srcky You got the update to the newest 41 version. This will be fixed after the rebase I guess.

**Comment by philippun1** [comment]
I merged the latest upstream/master into this branch, there are some regressions at the moment.

**Comment by yochananmarqos** [comment]
Which commit is this now based from? It will neither apply from e4a71fa nor 1e46333.

**Comment by philippun1** [comment]
@yochananmarqos I merged upstream/master directly into this branch, so it should be based on 1e46333.

**Comment by yochananmarqos** [comment]
That's what I thought, but applying this PR as a patch fails.

[PKGBUILD](https://pastebin.com/A7pa43Ey)
[Patch log](https://pastebin.com/zpqj0ZPb)

**Comment by chrisjbillington** [comment]
Github's patch generation must be generating a patch for the PR against the commit it is based on, rather than against the current state of branch it is to be merged into. Makes some kind of sense since the master branch is in flux so that patch could change moment-to-moment, but it leads to failure to apply in your case, even though the PR has no conflicts and could merge.

Rebasing this PR off current master instead of simply merging master into it would do the trick.

**Comment by philippun1** [comment]
@chrisjbillington I tried to rebase, but there were so many conflicts, every single commit had to be resolved by hand (the Settings.ui is HUGE). So I decided to merge the other way. Would a rebase on master after the merge help anything?

**Comment by chrisjbillington** [comment]
A rebase after the merge is undefined I think, since master is now a parent commit of this branch.

No point changing it to be a rebase instead unless this repository has  a strict rebasing-only-no-merging-master-into-branches policy. It would only make @yochananmarqos's obtaining a patch file easier, but he can ask git for a diff between this branch and master himself to make a patch file, which is easier than you doing a rebase by the sounds of it!

**Comment by yochananmarqos** [comment]
@chrisjbillington Thanks, that'll do for now. 👍️

**Comment by PHLAK** [comment]
To ease the rebase you could squash (some or all) of your commits @philippun. Then rebase onto upstream `master`.

**Comment by jderose9** [comment]
@philippun1 Let me know when you are ready for me to merge. I don't think we need to cover every outstanding issue before doing so - I can spend some time on them or we can open additional PRs. If there's anything that just isn't going to work in the near term I can pull it for now.

I think ideally the commits will get squashed first. If you want to do that, the easiest thing probably be to branch the latest master and --squash merge your change into the new branch and open a new PR.

**Comment by philippun1** [comment]
@jderose9 You can merge the current branch if you want to. Isn't there a "squash and merge" feature for pull requests on github? If not, I can squash it into a new branch if you wish.

**Comment by SCN-Nate** [comment]
So is our work done? 
We got on 'master'

**Comment by dylanmtaylor** [comment]
This does not seem to be available on the gnome extension site yet?

**Comment by jhpratt** [comment]
That's correct. It still needs a release, and I _believe_ all releases get reviewed as well.

**Pull request merged**
